// Auto-generated by blockchain deploy script
import contractsData from './contracts.json';

export const DEPLOYED_ADDRESSES = contractsData.addresses;
export const CONTRACT_ABIS = contractsData.abis;
export const CHAIN_ID = contractsData.chainId;
export default contractsData;
